// src/app/pages/dashboard/dashboard.component.ts
import { Component } from '@angular/core';

interface StatCard {
  title: string;
  value: string;
  change: string;
  changeType: 'positive' | 'negative';
  icon: string;
}

interface RecentActivity {
  id: string;
  type: string;
  title: string;
  description: string;
  time: string;
  status: string;
}

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent {
  statCards: StatCard[] = [
    {
      title: 'Total Projects',
      value: '24',
      change: '+12%',
      changeType: 'positive',
      icon: 'folder'
    },
    {
      title: 'Active Inspections',
      value: '8',
      change: '+3',
      changeType: 'positive',
      icon: 'clipboard-check'
    },
    {
      title: 'Open Issues',
      value: '15',
      change: '-5',
      changeType: 'negative',
      icon: 'alert-triangle'
    },
    {
      title: 'Completed Tasks',
      value: '156',
      change: '+23%',
      changeType: 'positive',
      icon: 'check-circle'
    }
  ];

  recentActivities: RecentActivity[] = [
    {
      id: '1',
      type: 'inspection',
      title: 'Site Inspection Completed',
      description: 'Building A - Foundation inspection passed',
      time: '2 hours ago',
      status: 'completed'
    },
    {
      id: '2',
      type: 'issue',
      title: 'New Issue Reported',
      description: 'Safety concern identified in Zone 3',
      time: '4 hours ago',
      status: 'pending'
    },
    {
      id: '3',
      type: 'project',
      title: 'Project Milestone Reached',
      description: 'Phase 1 construction completed',
      time: '1 day ago',
      status: 'completed'
    },
    {
      id: '4',
      type: 'document',
      title: 'Document Updated',
      description: 'Safety protocols revised and uploaded',
      time: '2 days ago',
      status: 'completed'
    }
  ];

  getStatusColor(status: string): string {
    switch (status) {
      case 'completed':
        return 'bg-green-100 text-green-800';
      case 'pending':
        return 'bg-yellow-100 text-yellow-800';
      case 'in-progress':
        return 'bg-blue-100 text-blue-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  }
} 
<div class="space-y-6">
  <!-- Page Header -->
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-2xl font-bold text-gray-900">Dashboard</h1>
      <p class="text-gray-600">Welcome back! Here's what's happening with your projects.</p>
    </div>
    <button class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors">
      New Project
    </button>
  </div>

  <!-- Stats Grid -->
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    <div *ngFor="let card of statCards" class="bg-white p-6 rounded-lg shadow-sm border border-gray-200">
      <div class="flex items-center justify-between">
        <div>
          <p class="text-sm font-medium text-gray-600">{{ card.title }}</p>
          <p class="text-2xl font-bold text-gray-900">{{ card.value }}</p>
        </div>
        <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
          <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path *ngIf="card.icon === 'folder'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-5l-2-2H5a2 2 0 00-2 2z"></path>
            <path *ngIf="card.icon === 'clipboard-check'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"></path>
            <path *ngIf="card.icon === 'alert-triangle'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z"></path>
            <path *ngIf="card.icon === 'check-circle'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
          </svg>
        </div>
      </div>
      <div class="mt-4 flex items-center">
        <span [class]="card.changeType === 'positive' ? 'text-green-600' : 'text-red-600'" class="text-sm font-medium">
          {{ card.change }}
        </span>
        <span class="text-sm text-gray-500 ml-2">from last month</span>
      </div>
    </div>
  </div>

  <!-- Recent Activity -->
  <div class="bg-white rounded-lg shadow-sm border border-gray-200">
    <div class="px-6 py-4 border-b border-gray-200">
      <h2 class="text-lg font-semibold text-gray-900">Recent Activity</h2>
    </div>
    <div class="p-6">
      <div class="space-y-4">
        <div *ngFor="let activity of recentActivities" class="flex items-start space-x-4">
          <div class="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center flex-shrink-0">
            <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path *ngIf="activity.type === 'inspection'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"></path>
              <path *ngIf="activity.type === 'issue'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z"></path>
              <path *ngIf="activity.type === 'project'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-5l-2-2H5a2 2 0 00-2 2z"></path>
              <path *ngIf="activity.type === 'document'" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
            </svg>
          </div>
          <div class="flex-1 min-w-0">
            <div class="flex items-center justify-between">
              <p class="text-sm font-medium text-gray-900">{{ activity.title }}</p>
              <span [class]="getStatusColor(activity.status)" class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium">
                {{ activity.status }}
              </span>
            </div>
            <p class="text-sm text-gray-600">{{ activity.description }}</p>
            <p class="text-xs text-gray-500 mt-1">{{ activity.time }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// src/pages/Dashboard.tsx

import { motion } from 'framer-motion';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { 
  Building, 
  CheckSquare, 
  AlertTriangle, 
  FileText, 
  TrendingUp,
  Clock,
  Users,
  Target
} from 'lucide-react';

const Dashboard = () => {
  const stats = [
    { title: 'Active Projects', value: '12', icon: Building, color: 'from-blue-500 to-blue-600', change: '+2' },
    { title: 'Inspections Due', value: '24', icon: CheckSquare, color: 'from-green-500 to-green-600', change: '+5' },
    { title: 'Open Issues', value: '8', icon: AlertTriangle, color: 'from-orange-500 to-orange-600', change: '-3' },
    { title: 'Documents', value: '156', icon: FileText, color: 'from-purple-500 to-purple-600', change: '+12' },
  ];

  const recentProjects = [
    { name: 'Metro Station Alpha', progress: 85, status: 'On Track', priority: 'High' },
    { name: 'Bridge Construction Beta', progress: 60, status: 'Delayed', priority: 'Medium' },
    { name: 'Highway Expansion Gamma', progress: 95, status: 'Near Complete', priority: 'High' },
    { name: 'Water Treatment Plant', progress: 30, status: 'Starting', priority: 'Low' },
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        duration: 0.5,
        ease: "easeOut"
      }
    }
  };

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="space-y-6"
    >
      <motion.div variants={itemVariants}>
        <h1 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-600 bg-clip-text text-transparent">
          Dashboard
        </h1>
        <p className="text-gray-600 mt-2">Welcome back! Here's what's happening with your projects.</p>
      </motion.div>

      {/* Stats Grid */}
      <motion.div 
        variants={containerVariants}
        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6"
      >
        {stats.map((stat, index) => (
          <motion.div key={stat.title} variants={itemVariants}>
            <Card className="relative overflow-hidden hover:shadow-lg transition-all duration-300 group border-0 bg-white/70 backdrop-blur-sm">
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <div className={`p-2 rounded-lg bg-gradient-to-r ${stat.color} text-white`}>
                    <stat.icon className="h-5 w-5" />
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    {stat.change}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-1">
                  <motion.p 
                    className="text-2xl font-bold"
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ delay: index * 0.1 + 0.3, type: "spring", stiffness: 200 }}
                  >
                    {stat.value}
                  </motion.p>
                  <p className="text-sm text-gray-600">{stat.title}</p>
                </div>
              </CardContent>
              
              <motion.div
                className={`absolute inset-x-0 bottom-0 h-1 bg-gradient-to-r ${stat.color}`}
                initial={{ scaleX: 0 }}
                animate={{ scaleX: 1 }}
                transition={{ delay: index * 0.1 + 0.5, duration: 0.6 }}
              />
            </Card>
          </motion.div>
        ))}
      </motion.div>

      {/* Recent Projects */}
      <motion.div variants={itemVariants} className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="border-0 bg-white/70 backdrop-blur-sm shadow-lg">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Target className="h-5 w-5 text-blue-600" />
              Recent Projects
            </CardTitle>
            <CardDescription>Track progress of your ongoing projects</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {recentProjects.map((project, index) => (
              <motion.div
                key={project.name}
                initial={{ x: -20, opacity: 0 }}
                animate={{ x: 0, opacity: 1 }}
                transition={{ delay: index * 0.1 + 0.6 }}
                className="space-y-2 p-3 rounded-lg hover:bg-blue-50/50 transition-colors"
              >
                <div className="flex items-center justify-between">
                  <h4 className="font-medium text-sm">{project.name}</h4>
                  <Badge 
                    variant={project.status === 'On Track' ? 'default' : 
                            project.status === 'Delayed' ? 'destructive' : 
                            project.status === 'Near Complete' ? 'default' : 'secondary'}
                    className="text-xs"
                  >
                    {project.status}
                  </Badge>
                </div>
                <div className="space-y-1">
                  <div className="flex justify-between text-xs text-gray-600">
                    <span>Progress</span>
                    <span>{project.progress}%</span>
                  </div>
                  <Progress 
                    value={project.progress} 
                    className="h-2"
                  />
                </div>
              </motion.div>
            ))}
          </CardContent>
        </Card>

        <Card className="border-0 bg-white/70 backdrop-blur-sm shadow-lg">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Clock className="h-5 w-5 text-orange-600" />
              Recent Activity
            </CardTitle>
            <CardDescription>Latest updates and notifications</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {[
              { action: 'Inspection completed', project: 'Metro Station Alpha', time: '2 hours ago' },
              { action: 'Issue reported', project: 'Bridge Construction Beta', time: '4 hours ago' },
              { action: 'Document uploaded', project: 'Highway Expansion Gamma', time: '6 hours ago' },
              { action: 'Checklist updated', project: 'Water Treatment Plant', time: '1 day ago' },
            ].map((activity, index) => (
              <motion.div
                key={index}
                initial={{ y: 20, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ delay: index * 0.1 + 0.8 }}
                className="flex items-start gap-3 p-3 rounded-lg hover:bg-orange-50/50 transition-colors"
              >
                <div className="w-2 h-2 bg-orange-500 rounded-full mt-2"></div>
                <div className="flex-1 space-y-1">
                  <p className="text-sm font-medium">{activity.action}</p>
                  <p className="text-xs text-gray-600">{activity.project}</p>
                  <p className="text-xs text-gray-500">{activity.time}</p>
                </div>
              </motion.div>
            ))}
          </CardContent>
        </Card>
      </motion.div>
    </motion.div>
  );
};

export default Dashboard;
